spring:
  application:
    name: glamo-user-service
  datasource:
    url: jdbc:postgresql://localhost:2021/user-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080
  address: 0.0.0.0
jwt:
  secret: YWxnb3JpdGhtc2VjdXJla2V5Zm9yamV0Z2VuZXJhdGVkZm9yaHM1Ng==
  expiration: 36000000



logging:
  level:
    org.springframework.security: DEBUG